import './styles.css';
import './branding.css';
import './hero.css';
import { heroHighlightMarkup } from './hero-art.js';
import { viewFromPath,viewPath } from './client-navigation.js';
import { initBranding, applyBranding, brandMarkup, getBranding } from './branding.js';
import { api,ensureDevice,forgetDevice,watchChanges } from './api.js';
import { $,icon,toast,busy,modal,bookingSummary,badge,profileAvatar } from './ui.js';
import { money,time,date,dayKey,addDays,escape,normalizePhone,phoneMask } from './utils.js';

const state={catalog:null,step:1,services:[],barber:'',day:dayKey(),start:null,slots:[],loading:false,view:viewFromPath(location.pathname),connected:false};
try{state.contact=JSON.parse(localStorage.getItem('barber-contact')||'{}');}catch{state.contact={};}
state.contact??={};
let slotRequest=0,refreshing=false;
const chosen=()=>state.catalog.services.filter(s=>state.services.includes(s.id));
const total=()=>chosen().reduce((n,s)=>n+Number(s.price),0);
const duration=()=>chosen().reduce((n,s)=>n+s.duration,0);
const availableBarbers=()=>state.catalog.barbers.filter(b=>state.services.every(s=>state.catalog.barber_services.some(bs=>bs.barber_id===b.id&&bs.service_id===s)));
function navigate(view,{replace=false}={}){state.view=view;if(location.pathname!==viewPath(view))history[replace?'replaceState':'pushState'](null,'',viewPath(view));shell();return render();}
window.addEventListener('popstate',()=>{state.view=viewFromPath(location.pathname);shell();if(state.catalog)render();});

function shell(){
 $('#app').innerHTML=`<header class="site-header"><a class="brand" href="/" data-brand-home aria-label="${escape(getBranding().shop_name)}, início">${brandMarkup()}</a><nav><button class="nav-link ${state.view==='booking'?'active':''}" data-view="booking">Agendar</button><button class="nav-link ${state.view==='history'?'active':''}" data-view="history">${icon('calendar',16)} Meus agendamentos</button><a class="owner-link" href="/admin.html" aria-label="Acessar painel do proprietário">${icon('user',18)}<span>Painel</span></a></nav></header><main id="main"></main><footer class="site-footer"><span><span data-shop-name>${escape(getBranding().shop_name)}</span> <span class="muted">· Cuidado nos detalhes.</span></span><button class="text-btn" id="footer-hours">Ver horários disponíveis</button><a href="/admin.html">Área do proprietário ${icon('arrow',14)}</a></footer>`;
 document.querySelectorAll('[data-view]').forEach(el=>el.onclick=()=>navigate(el.dataset.view));
 $('#footer-hours').onclick=()=>{state.step=state.services.length?2:1;navigate('booking');document.querySelector('.booking-section')?.scrollIntoView({behavior:'smooth',block:'start'});};
}
function connection(){return `<span class="live-status"><i class="${state.connected?'connected':''}"></i><span>${state.connected?'Agenda em tempo real':'Agenda sincronizando'}</span></span>`;}
function progress(){return `<div class="steps" aria-label="Etapas do agendamento">${['Serviços','Dia e horário','Seus dados'].map((label,i)=>`<button class="step ${state.step===i+1?'current':''} ${state.step>i+1?'complete':''}" data-step="${i+1}" ${i+1>state.step?'disabled':''}><span>${state.step>i+1?icon('check',14):`0${i+1}`}</span>${label}</button>`).join('')}</div>`;}
function render(){
 if(state.view==='history')return renderHistory();
 const services=chosen();const barber=state.catalog.barbers.find(b=>b.id===state.barber);
 $('#main').innerHTML=`<section class="hero"><div><div class="eyebrow"><span class="red-line"></span> FEITO PARA O SEU RITMO</div><h1>Seu horário.<br><span>Do seu jeito.</span></h1><p>Escolha seu serviço, encontre o melhor horário<br class="desktop-only"> e deixe o resto com a gente.</p></div><div class="hero-highlight" data-hero-highlight>${heroHighlightMarkup(getBranding())}</div></section><section class="booking-section"><div class="section-bar"><div><span class="eyebrow dark">AGENDAMENTO ONLINE</span><h2>Reserve seu próximo cuidado.</h2></div>${connection()}</div>${progress()}<div class="booking-grid"><div class="booking-work" id="step-content">${state.step===1?serviceStep():state.step===2?scheduleStep():contactStep()}</div><aside class="booking-summary"><div class="eyebrow dark">DO SEU JEITO</div><h3>Seu agendamento</h3><div class="summary-selections">${services.length?services.map(s=>`<div class="selected-service"><span>${escape(s.name)}<small>${s.duration} min</small></span><strong>${money(s.price)}</strong></div>`).join(''):'<div class="empty-summary">'+icon('scissors',30)+'<p>Seu próximo visual<br>começa aqui.</p></div>'}</div>${barber?`<div class="summary-line"><span>Profissional</span><strong>${escape(barber.name)}</strong></div>`:''}${state.start?`<div class="summary-line"><span>Data e horário</span><strong>${date(state.start)}<br>${time(state.start)}–${time(new Date(new Date(state.start).getTime()+duration()*60000))}</strong></div>`:''}<div class="summary-total"><span>Total estimado<small>${duration()?duration()+' minutos de cuidado':'Selecione seus serviços'}</small></span><strong>${money(total())}</strong></div><button id="continue" class="btn primary full" ${!services.length||(state.step===2&&!state.start)?'disabled':''}>${state.step===1?'Escolher horário':state.step===2?'Continuar':'Conferir agendamento'} ${icon('arrow',18)}</button><p class="secure-note">${icon('shield',14)} Sem cadastro. Simples assim.</p><div class="summary-help"><span>UM CUIDADO A MAIS</span><p>Seu histórico fica disponível neste navegador. Você também pode cancelar ou reagendar por aqui.</p></div></aside></div></section><section class="trust-strip"><div>${icon('clock',24)}<span>Respeito ao seu tempo<small>Horários reservados para você.</small></span></div><div>${icon('scissors',24)}<span>Cuidado em cada detalhe<small>Escolha os serviços do seu jeito.</small></span></div><div>${icon('calendar',24)}<span>Agenda sempre atualizada<small>Disponibilidade direto da barbearia.</small></span></div></section>`;
 bindStep();
 document.querySelectorAll('[data-step]').forEach(el=>el.onclick=()=>{state.step=Number(el.dataset.step);render();});
 $('#continue').onclick=()=>{if(state.step===1){state.step=2;const barbers=availableBarbers();if(!barbers.some(b=>b.id===state.barber))state.barber=barbers[0]?.id||'';state.start=null;render();loadSlots();}else if(state.step===2){state.step=3;render();}else confirmBooking();};
}
function serviceStep(){return `<div class="step-heading"><span class="step-index">01</span><div><h3>O que vamos fazer hoje?</h3><p>Combine serviços e monte seu atendimento.</p></div></div><div class="service-grid">${state.catalog.services.map((s,i)=>`<button class="service-card ${state.services.includes(s.id)?'selected':''}" data-service="${s.id}" aria-pressed="${state.services.includes(s.id)}"><div class="service-card-top"><span class="service-number">0${i+1}</span><span class="select-check">${icon('check',14)}</span></div><span class="service-name">${escape(s.name)}</span><span class="service-desc">${escape(s.description)}</span><div class="service-card-bottom"><strong>${money(s.price)}</strong><span>${icon('clock',13)} ${s.duration} min</span></div></button>`).join('')}</div><p class="small-note">${icon('plus',14)} Você pode selecionar mais de um serviço.</p>`;}
function scheduleStep(){const barbers=availableBarbers();return `<div class="step-heading"><span class="step-index">02</span><div><h3>Um horário só seu.</h3><p>Escolha quem vai atender e quando você vem.</p></div></div><label class="field-label">Seu profissional</label><div class="barber-choice">${barbers.map(b=>`<button class="barber-card ${state.barber===b.id?'selected':''}" data-barber="${b.id}" aria-pressed="${state.barber===b.id}">${profileAvatar(b)}<span>${escape(b.name)}<small>Profissional</small></span>${icon('check',16)}</button>`).join('')||'<p class="empty">Nenhum profissional realiza todos os serviços selecionados. Volte e ajuste sua escolha.</p>'}</div><div class="date-heading"><label class="field-label" for="booking-date">Escolha o dia</label><input id="booking-date" type="date" min="${dayKey()}" max="${addDays(dayKey(),180)}" value="${state.day}"></div><div class="day-strip"><button class="day-nav" id="prev-week" aria-label="Semana anterior" ${state.day===dayKey()?'disabled':''}>‹</button>${Array.from({length:7},(_,i)=>{const d=addDays(state.day,i);const obj=new Date(`${d}T12:00:00-03:00`);return `<button class="day-card ${d===state.day?'selected':''}" data-day="${d}"><span>${new Intl.DateTimeFormat('pt-BR',{weekday:'short'}).format(obj).replace('.','')}</span><strong>${obj.getDate()}</strong><small>${new Intl.DateTimeFormat('pt-BR',{month:'short'}).format(obj).replace('.','')}</small></button>`;}).join('')}<button class="day-nav" id="next-week" aria-label="Próxima semana">›</button></div><div class="times-heading"><label class="field-label">Horários disponíveis</label><span>${duration()} min de atendimento</span></div><div id="slots" aria-live="polite">${slotMarkup()}</div><p class="small-note">${icon('clock',14)} Horários no fuso de São Paulo. O intervalo de almoço é reservado.</p>`;}
function slotMarkup(){return state.loading?'<div class="skeleton-line"></div><div class="skeleton-line short"></div>':state.slots.length?`<div class="slot-grid">${state.slots.map(s=>`<button class="slot ${s.start===state.start?'selected':''}" data-slot="${escape(s.start)}" aria-pressed="${s.start===state.start}">${time(s.start)}</button>`).join('')}</div>`:'<div class="empty-times">'+icon('calendar',28)+'<strong>Nenhum horário disponível neste dia.</strong><span>Experimente outra data ou outro profissional.</span></div>';}
function contactStep(){return `<div class="step-heading"><span class="step-index">03</span><div><h3>Como podemos chamar você?</h3><p>Falta pouco. Confira seus dados antes de confirmar.</p></div></div><form id="contact-form" class="contact-form"><label>Seu nome<input id="customer-name" name="name" autocomplete="name" required minlength="2" maxlength="100" placeholder="Nome e sobrenome" value="${escape(state.contact.name)}"></label><label>Celular com DDD<input id="customer-phone" name="phone" inputmode="tel" autocomplete="tel" required placeholder="(15) 99999-9999" value="${escape(state.contact.phone)}"></label><label class="consent"><input id="reminder-consent" type="checkbox" ${state.contact.consent?'checked':''}><span>Quero receber lembretes deste agendamento pelo WhatsApp.<small>Opcional. Você pode agendar sem aceitar.</small></span></label></form><div class="privacy-note">${icon('shield',22)}<div><strong>Seus agendamentos, no seu dispositivo.</strong><p>Vamos lembrar seu nome e celular neste navegador para facilitar a próxima visita. Limpar os dados ou trocar de aparelho pode remover o acesso local ao histórico.</p></div></div>`;}
function bindStep(){
 document.querySelectorAll('[data-service]').forEach(el=>el.onclick=()=>{const id=el.dataset.service;state.services=state.services.includes(id)?state.services.filter(x=>x!==id):[...state.services,id];state.start=null;render();});
 document.querySelectorAll('[data-barber]').forEach(el=>el.onclick=()=>{state.barber=el.dataset.barber;state.start=null;render();loadSlots();});
 document.querySelectorAll('[data-day]').forEach(el=>el.onclick=()=>selectDay(el.dataset.day));
 $('#booking-date')?.addEventListener('change',e=>selectDay(e.target.value));
 $('#prev-week')?.addEventListener('click',()=>selectDay(addDays(state.day,-7)<dayKey()?dayKey():addDays(state.day,-7)));
 $('#next-week')?.addEventListener('click',()=>selectDay(addDays(state.day,7)));
 bindSlots();
 $('#customer-name')?.addEventListener('input',e=>state.contact.name=e.target.value);
 $('#customer-phone')?.addEventListener('input',e=>{e.target.value=phoneMask(e.target.value);state.contact.phone=e.target.value;});
 $('#reminder-consent')?.addEventListener('change',e=>state.contact.consent=e.target.checked);
 $('#contact-form')?.addEventListener('submit',e=>{e.preventDefault();confirmBooking();});
}
function bindSlots(){document.querySelectorAll('[data-slot]').forEach(el=>el.onclick=()=>{state.start=el.dataset.slot;render();});}
function selectDay(day){if(!day||day<dayKey()||day>addDays(dayKey(),180))return;state.day=day;state.start=null;render();loadSlots();}
async function loadSlots(){
 if(!state.barber||!state.services.length)return;
 const request=++slotRequest;state.loading=true;if($('#slots'))$('#slots').innerHTML=slotMarkup();
 try{const slots=await api('slots',{barber_id:state.barber,day:state.day,services:state.services});if(request!==slotRequest)return;state.slots=slots;state.loading=false;if(state.start&&!slots.some(s=>s.start===state.start)){state.start=null;toast('O horário selecionado ficou indisponível. Escolha outro.');if(state.step===3){state.step=2;render();}}if($('#slots')){$('#slots').innerHTML=slotMarkup();bindSlots();}const btn=$('#continue');if(state.step===2&&btn)btn.disabled=!state.start;}
 catch(e){if(request!==slotRequest)return;state.loading=false;state.slots=[];if($('#slots'))$('#slots').innerHTML=`<div class="inline-error">${escape(e.message)} <button id="retry-slots" class="text-btn">Tentar novamente</button></div>`;$('#retry-slots')?.addEventListener('click',loadSlots);}
}
function confirmBooking(){
 if(!$('#contact-form').reportValidity())return;
 let phone;try{phone=normalizePhone(state.contact.phone);}catch(e){return toast(e.message,true);}
 const preview={items:chosen(),barber_name:state.catalog.barbers.find(b=>b.id===state.barber)?.name,starts_at:state.start,ends_at:new Date(new Date(state.start).getTime()+duration()*60000).toISOString(),customer_name:state.contact.name.trim(),customer_phone:phone,total:total()};
 modal('Tudo certo com seu horário?',`<p class="modal-intro">Confira os detalhes. A reserva será confirmada ao continuar.</p>${bookingSummary(preview)}`,{confirm:'Confirmar agendamento',onConfirm:async()=>{
  await ensureDevice();
  const payload={name:preview.customer_name,phone,barber_id:state.barber,services:state.services,start:state.start,consent:!!state.contact.consent};
  let pending;try{pending=JSON.parse(localStorage.getItem('barber-pending-booking')||'null');}catch{pending=null;}
  const fingerprint=JSON.stringify(payload);const idempotency=pending?.fingerprint===fingerprint?pending.key:crypto.randomUUID();
  localStorage.setItem('barber-pending-booking',JSON.stringify({fingerprint,key:idempotency}));
  try{
   const b=await api('book',{...payload,idempotency_key:idempotency});localStorage.removeItem('barber-pending-booking');localStorage.setItem('barber-contact',JSON.stringify(state.contact));
   state.step=1;state.services=[];state.start=null;await navigate('history',{replace:true});
   modal('Seu horário está reservado.',`<div class="success-stamp">${icon('check',32)}</div>${bookingSummary(b)}<p class="receipt-id">COMPROVANTE ${escape(b.id)}</p><p class="small-note">Acesse este comprovante em Meus agendamentos, neste dispositivo.</p>`);
  }catch(e){if(e.status===409){localStorage.removeItem('barber-pending-booking');state.step=2;state.start=null;render();loadSlots();}throw e;}
 }});
}
async function renderHistory(){
 $('#main').innerHTML=`<section class="history-page"><div class="section-bar"><div><span class="eyebrow dark">SEU PRÓXIMO CUIDADO</span><h1 class="page-title">Meus agendamentos<span>.</span></h1><p class="muted">Suas reservas e seu histórico, neste dispositivo.</p></div><button class="btn primary" id="new-booking">Novo agendamento ${icon('plus',18)}</button></div><div class="history-info">${icon('shield',20)}<p>Seu acesso está vinculado a este navegador. Limpar os dados ou mudar de aparelho não apaga os registros da barbearia, mas pode remover seu acesso local.</p><button class="text-btn" id="forget">Esquecer meus dados</button></div><div id="history-list"><div class="skeleton-line"></div><div class="skeleton-line"></div></div></section>`;
 $('#new-booking').onclick=()=>navigate('booking');
 $('#forget').onclick=()=>modal('Esquecer os dados deste dispositivo?',`<p>Seu nome, celular e chave de acesso serão removidos deste navegador. As reservas permanecem na barbearia e não serão canceladas.</p>`,{confirm:'Esquecer dados',onConfirm:async()=>{forgetDevice();state.contact={};await renderHistory();toast('Dados locais removidos.');}});
 try{
  await ensureDevice();const bookings=await api('mine');if(state.view!=='history')return;
  const future=bookings.filter(b=>new Date(b.starts_at)>new Date()&&['agendado','confirmado'].includes(b.status));const previous=bookings.filter(b=>!future.includes(b));
  $('#history-list').innerHTML=bookings.length?`${future.length?'<h3 class="history-group">Próximos atendimentos</h3>'+future.slice().reverse().map(historyCard).join(''):''}${previous.length?'<h3 class="history-group">Seu histórico</h3>'+previous.map(historyCard).join(''):''}`:`<div class="empty-state">${icon('calendar',44)}<h3>Seu próximo cuidado começa aqui.</h3><p>Você ainda não tem agendamentos neste dispositivo.</p><button class="btn primary" id="empty-book">Agendar agora ${icon('arrow',18)}</button></div>`;
  $('#empty-book')?.addEventListener('click',()=>{$('#new-booking').click();});
  document.querySelectorAll('[data-details]').forEach(el=>el.onclick=()=>modal('Detalhes do agendamento',bookingSummary(bookings.find(b=>b.id===el.dataset.details))));
  document.querySelectorAll('[data-cancel]').forEach(el=>el.onclick=()=>modal('Cancelar este horário?',`<p>O intervalo será liberado para outras pessoas. A reserva permanecerá no seu histórico.</p>`,{confirm:'Cancelar agendamento',onConfirm:async()=>{await api('cancel',{id:el.dataset.cancel});await renderHistory();toast('Agendamento cancelado.');}}));
  document.querySelectorAll('[data-reschedule]').forEach(el=>el.onclick=()=>reschedule(bookings.find(b=>b.id===el.dataset.reschedule)));
 }catch(e){if($('#history-list'))$('#history-list').innerHTML=`<div class="inline-error">${escape(e.message)} <button class="text-btn" id="retry-history">Tentar novamente</button></div>`;$('#retry-history')?.addEventListener('click',renderHistory);}
}
function historyCard(b){const can=['agendado','confirmado'].includes(b.status)&&new Date(b.starts_at)>new Date();return `<article class="history-card"><div class="history-date">${icon('calendar',24)}<strong>${date(b.starts_at)}</strong><span>${time(b.starts_at)}–${time(b.ends_at)}</span></div><div class="history-detail">${badge(b.status)}<h3>${escape(b.items.map(s=>s.name).join(' + '))}</h3><p>${escape(b.barber_name)} · ${b.duration} min · ${money(b.total)}</p><small>#${escape(b.id.slice(0,8).toUpperCase())}</small></div><div class="history-actions"><button class="btn secondary small" data-details="${b.id}">Detalhes</button>${can?`<button class="btn secondary small" data-reschedule="${b.id}">Reagendar</button><button class="text-btn danger" data-cancel="${b.id}">Cancelar</button>`:''}</div></article>`;}
async function reschedule(b){
 let selected=null;const dialog=modal('Encontrar um novo horário',`<p>Seu horário atual permanece reservado até confirmar um novo.</p><label class="field-label" for="reschedule-date">Nova data</label><input id="reschedule-date" type="date" value="${dayKey(b.starts_at)}" min="${dayKey()}" max="${addDays(dayKey(),180)}"><div id="reschedule-slots" class="slot-grid spaced"></div>`,{confirm:'Confirmar novo horário',onConfirm:async()=>{if(!selected)throw new Error('Selecione um horário.');await api('reschedule',{id:b.id,barber_id:b.barber_id,start:selected});await renderHistory();toast('Seu horário foi atualizado.');}});
 let request=0;const load=async()=>{const n=++request;selected=null;dialog.querySelector('[data-confirm]').disabled=true;const target=dialog.querySelector('#reschedule-slots');target.innerHTML='<p>Consultando a agenda…</p>';try{const slots=await api('slots',{barber_id:b.barber_id,day:dialog.querySelector('#reschedule-date').value,booking_id:b.id});if(n!==request||!dialog.isConnected)return;target.innerHTML=slots.length?slots.map(s=>`<button class="slot" data-new-slot="${escape(s.start)}">${time(s.start)}</button>`).join(''):'<p>Nenhum horário disponível. Escolha outra data.</p>';target.querySelectorAll('button').forEach(el=>el.onclick=()=>{selected=el.dataset.newSlot;target.querySelectorAll('button').forEach(x=>x.classList.toggle('selected',x===el));dialog.querySelector('[data-confirm]').disabled=false;});}catch(e){target.textContent=e.message;}};
 dialog.querySelector('#reschedule-date').onchange=load;await load();
}
async function start(){
 shell();$('#main').innerHTML='<section class="loading-page"><div class="loader"></div><p>Preparando sua próxima visita…</p></section>';
 try{state.catalog=await api('catalog');applyBranding(state.catalog);render();await ensureDevice();watchChanges(async()=>{if(refreshing)return;refreshing=true;try{state.catalog=await api('catalog');applyBranding(state.catalog);if(state.view==='history'&&!document.querySelector('dialog'))await renderHistory();else if(state.step===2||state.step===3)await loadSlots();}catch{/* consulta será repetida ao reconectar */}finally{refreshing=false;}},connected=>{state.connected=connected;document.querySelectorAll('.live-status').forEach(el=>el.outerHTML=connection());});}
 catch(e){$('#main').innerHTML=`<section class="empty-state"><h1>Não conseguimos carregar a agenda.</h1><p>${escape(e.message)}</p><button class="btn primary" id="retry-app">Tentar novamente</button></section>`;$('#retry-app').onclick=start;}
}
initBranding();
start();
