import { escape, phoneMask } from './utils.js';

export function whatsappSettingsMarkup(status) {
  const w = status?.whatsapp ?? {};
  return `<section class="panel-card special-panel whatsapp-settings"><div class="panel-heading"><div><h3>Lembretes automáticos no WhatsApp</h3><p>30 minutos antes do atendimento, mesmo com o painel fechado.</p></div><span class="badge ${w.configured ? 'confirmado' : 'pending'}">${w.configured ? w.automatic_enabled === false ? 'Pausados' : 'Prontos para enviar' : 'Conexão pendente'}</span></div><p>O cliente recebe um lembrete se autorizou o WhatsApp ao agendar. Cancelamentos e mudanças de horário atualizam a fila automaticamente.</p>${w.sender_phone ? `<p><strong>Remetente:</strong> ${escape(phoneMask(w.sender_phone))}${w.verified_name ? ` · ${escape(w.verified_name)}` : ''}</p>` : '<p>Conecte uma conta WhatsApp Business para ativar o envio automático.</p>'}<div class="detail-actions"><button id="connect-whatsapp" class="btn primary small">${w.configured ? 'Atualizar conexão' : 'Conectar WhatsApp'}</button>${w.configured ? `<button id="toggle-whatsapp" class="btn secondary small">${w.automatic_enabled === false ? 'Ativar lembretes automáticos' : 'Pausar lembretes automáticos'}</button>` : ''}</div><p class="fine-print">Verificação a cada minuto. Reservas feitas com menos de 30 minutos de antecedência recebem o lembrete na próxima verificação. A entrega depende do WhatsApp; acompanhe o resultado em Notificações.</p></section>`;
}

export function whatsappConnectionFields(status) {
  const w = status?.whatsapp ?? {};
  const secret = (name, label, present) => `<label>${label}<input name="${name}" type="password" autocomplete="new-password" maxlength="${name === 'access_token' ? 4096 : 200}" ${name === 'access_token' && !present ? 'required' : ''} placeholder="${present ? 'Já salvo. Deixe em branco para manter.' : 'Cole aqui, apenas neste painel.'}"></label>`;
  return `<p class="whatsapp-intro">Esta conexão é feita uma vez. Depois, os lembretes são enviados automaticamente.</p><ol class="whatsapp-steps"><li>Na Meta, habilite seu remetente WhatsApp Business e obtenha a autorização de envio e os IDs abaixo. <a href="https://developers.facebook.com/apps/" target="_blank" rel="noopener noreferrer">Abrir configuração na Meta ↗</a></li><li>Crie e aguarde a aprovação do modelo de lembrete em português, usando o texto indicado abaixo.</li><li>Preencha os dados e clique em <strong>Conectar e ativar</strong>. O sistema verifica a conta e o modelo sem enviar uma mensagem de teste.</li></ol><div class="form-row"><label>ID do telefone remetente<input name="phone_number_id" inputmode="numeric" pattern="[0-9]{5,30}" required value="${escape(w.phone_number_id)}"></label><label>ID da conta WhatsApp Business<input name="waba_id" inputmode="numeric" pattern="[0-9]{5,30}" required value="${escape(w.waba_id)}"></label></div>${secret('access_token','Autorização de envio (token da Meta)',w.has_token)}<div class="form-row"><label>Versão da API exibida na Meta<input name="graph_version" required pattern="v[0-9]{1,3}\\.0" placeholder="vXX.0" value="${escape(w.graph_version)}"></label><label>Nome do modelo de lembrete<input name="reminder_template" required pattern="[a-z0-9_]{1,100}" value="${escape(w.reminder_template || 'barber_booking_reminder')}"></label></div><details class="whatsapp-help"><summary>Texto para o modelo de lembrete (6 parâmetros)</summary><p>Use português do Brasil (pt_BR), parâmetros numerados e corpo de texto, sem mídia nem botões.</p><pre>Olá, {{1}}! Lembramos do seu atendimento na {{2}}.
Horário: {{3}}.
Serviços: {{4}}.
Profissional: {{5}}.
Consulte sua reserva no dispositivo em que agendou: {{6}}.</pre></details><details class="whatsapp-help"><summary>Retorno de entrega e avisos ao barbeiro (opcionais)</summary><p>Para acompanhar Entregue e Lido, configure o webhook na Meta com os dois campos abaixo.</p><label>URL de retorno<input readonly value="https://hvsqlrqegjbjqspaqcsc.supabase.co/functions/v1/whatsapp-webhook"></label>${secret('app_secret','Segredo do aplicativo Meta',w.has_app_secret)}${secret('verify_token','Código de verificação do retorno',w.has_verify_token)}<label>Modelo de avisos ao barbeiro<input name="owner_template" pattern="[a-z0-9_]{1,100}" value="${escape(w.owner_template)}" placeholder="Opcional: barber_owner_update"></label><p>Este modelo deve ter 9 parâmetros numerados: evento, cliente, celular, serviços, data e hora, valor, ID da reserva, dia e resumo da agenda. Se o barbeiro usar o mesmo número do remetente, não poderá receber esses avisos nele.</p></details><label class="checkbox-inline"><input name="automatic_enabled" type="checkbox" ${w.automatic_enabled !== false ? 'checked' : ''}> Ativar lembretes automáticos 30 minutos antes</label><p class="fine-print">O token fica criptografado no servidor e não volta para a página. A Meta pode cobrar pelo uso da plataforma conforme sua conta.</p>`;
}
